import { EventEmitter } from 'events'
EventEmitter.defaultMaxListeners = 20

import path from 'node:path'
import { serve } from '@hono/node-server'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { serveStatic } from '@hono/node-server/serve-static'
import { initializeDatabase } from './db/schema'
import { createRepoRoutes } from './routes/repos'
import { createSettingsRoutes } from './routes/settings'
import { createScheduleRoutes } from './routes/schedules'
import { createPermissionRuleRoutes } from './routes/permission-rules'
import { createUntrackedSuggestionsRoutes } from './routes/untracked-suggestions'
import { createHealthRoutes } from './routes/health'
import { createTTSRoutes, cleanupExpiredCache } from './routes/tts'
import { createFileRoutes } from './routes/files'
import { createRegistryRoutes } from './routes/registry'
import { createConfigFileRoutes } from './routes/config-files'
import { createProvidersRoutes } from './routes/providers'
import { createPreviewRoutes } from './routes/preview'
import { createCommandRunRoutes } from './routes/command-runs'
import { createSearchRoutes } from './routes/search'
import { createClientLogRoutes } from './routes/client-logs'
import { createSessionStatusRoutes } from './routes/session-status'
import { createChatQueueRoutes } from './routes/chat-queue'
import { getEmbeddedAsset, hasEmbeddedAssets } from './services/embedded-frontend'
import { stopConverter } from './services/doc-converter'
import { startScheduleRunner } from './services/scheduler'
import { startSessionStatusPoller, stopSessionStatusPoller } from './services/session-status'
import { startGitCommitIndexer, stopGitCommitIndexer } from './services/git-indexer'
import { migrateCommandRunsToFiles } from './services/command-run-migration'
import { startAutomationWatcher, stopAutomationWatcher } from './services/automation-watcher'
import { ensureDirectoryExists, writeFileContent, readFileContent, fileExists } from './services/file-operations'
import { SettingsService } from './services/settings'
import { mergeDefaultMcpEntries, warmUpAgentBrowserDaemon, writeRepoOpenCodeConfig, repoAgentBrowserNamespace } from './services/default-mcp'
import { migrateConfigMapToFiles } from './services/config-migration'
import { opencodeServerManager, prepareBackendPort, installWindowsShutdownWatchdog } from './services/opencode-single-server'
import { cleanupOrphanedDirectories } from './services/repo'
import { listRepos } from './db/queries'
import { openApiSpec } from './services/api-docs'
import { proxyRequest, setProxyDb } from './services/proxy'
import { logger } from './utils/logger'
import { 
  getWorkspacePath, 
  getReposPath, 
  getConfigPath,
  getOpenCodeConfigFilePath,
  getDatabasePath,
  ENV
} from '@opencode-webui/shared'

let { PORT, HOST } = ENV.SERVER
const DB_PATH = getDatabasePath()

async function ensureEnvFile(): Promise<void> {
  const envPath = path.resolve(process.cwd(), '.env')
  if (await fileExists(envPath)) {
    logger.info('.env found, using existing env file')
    try {
      const { config } = await import('dotenv')
      config({ path: envPath, override: true })
      const envPort = process.env.PORT ? parseInt(process.env.PORT, 10) : NaN
      if (!Number.isNaN(envPort)) PORT = envPort
      const envHost = process.env.HOST
      if (envHost) HOST = envHost
    } catch {}
    return
  }
  try {
    const content = [
      `# Generated by opencode-webui on ${new Date().toISOString()}`,
      `PORT=${PORT}`,
      `HOST=${HOST}`,
      `OPENCODE_SERVER_PORT=${ENV.OPENCODE.PORT}`,
      `OPENCODE_HOST=${ENV.OPENCODE.HOST}`,
      `DATABASE_PATH=${getDatabasePath()}`,
      `WORKSPACE_PATH=${getWorkspacePath()}`,
      `CORS_ORIGIN=http://localhost:${PORT}`,
      `NODE_ENV=development`,
    ].join('\n') + '\n'
    await writeFileContent(envPath, content)
    logger.info('Created .env with defaults (program handling, not script copy)')
    try {
      const { config } = await import('dotenv')
      config({ path: envPath, override: true })
      const envPort = process.env.PORT ? parseInt(process.env.PORT, 10) : NaN
      if (!Number.isNaN(envPort)) PORT = envPort
      const envHost = process.env.HOST
      if (envHost) HOST = envHost
    } catch {}
  } catch (error) {
    logger.warn('Failed to ensure .env file:', error)
  }
}

process.on('unhandledRejection', (reason) => {
  logger.error('Unhandled promise rejection (preventing crash):', reason)
})
process.on('uncaughtException', (error) => {
  logger.error('Uncaught exception (preventing crash):', error)
})

const app = new Hono()

app.use('/*', cors({
  origin: '*',
  allowMethods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
  allowHeaders: ['Content-Type', 'Authorization'],
}))

const db = initializeDatabase(DB_PATH)
setProxyDb(db)

void migrateCommandRunsToFiles(db).catch((error) => {
  logger.error('Command runs file migration failed (will retry on next boot):', error)
})

const DEFAULT_OPENCODE_CONFIG = {
  $schema: 'https://opencode.ai/config.json',
  theme: 'opencode',
  autoupdate: true,
  share: 'disabled',
  keybinds: {
    leader: 'ctrl+x',
    app_exit: 'ctrl+c,ctrl+d,<leader>q',
    editor_open: '<leader>e',
    theme_list: '<leader>t',
    sidebar_toggle: '<leader>b',
    status_view: '<leader>s',
    session_export: '<leader>x',
    session_new: '<leader>n',
    session_list: '<leader>l',
    session_timeline: '<leader>g',
    session_share: 'none',
    session_unshare: 'none',
    session_interrupt: 'escape',
    session_compact: '<leader>c',
    messages_page_up: 'pageup',
    messages_page_down: 'pagedown',
    messages_half_page_up: 'ctrl+alt+u',
    messages_half_page_down: 'ctrl+alt+d',
    messages_first: 'ctrl+g,home',
    messages_last: 'ctrl+alt+g,end',
    messages_copy: '<leader>y',
    messages_undo: '<leader>u',
    messages_redo: '<leader>r',
    messages_toggle_conceal: '<leader>h',
    model_list: '<leader>m',
    model_cycle_recent: 'f2',
    model_cycle_recent_reverse: 'shift+f2',
    command_list: 'ctrl+p',
    agent_list: '<leader>a',
    agent_cycle: 'tab',
    agent_cycle_reverse: 'shift+tab',
    input_clear: 'ctrl+c',
    input_forward_delete: 'ctrl+d',
    input_paste: 'ctrl+v',
    input_submit: 'return',
    input_newline: 'shift+return,ctrl+j',
    history_previous: 'up',
    history_next: 'down',
    session_child_cycle: '<leader>right',
    session_child_cycle_reverse: '<leader>left',
    terminal_suspend: 'ctrl+z',
  },
  permission: {
    bash: {
      '*': 'allow',
    },
  },
}

async function ensureDefaultConfigExists(): Promise<void> {
  const settingsService = new SettingsService(db)
  const configs = settingsService.getOpenCodeConfigs()
  
  if (configs.configs.length === 0) {
    logger.info('No OpenCode configs found, creating default config')
    settingsService.createOpenCodeConfig({
      name: 'default',
      content: mergeDefaultMcpEntries(DEFAULT_OPENCODE_CONFIG),
      isDefault: true,
    })
    logger.info('Created default OpenCode config')
  }
}

async function ensureGlobalRulesFile(): Promise<void> {
  const source = path.join(process.cwd(), 'docs', 'agent-domain-guide.md')
  const target = path.join(getConfigPath(), 'AGENTS.md')
  if (!(await fileExists(source))) return
  if (await fileExists(target)) return
  const content = await readFileContent(source)
  await writeFileContent(target, content)
  logger.info(`Installed global rules file: ${target}`)
}

async function syncDefaultConfigToDisk(): Promise<void> {
  const settingsService = new SettingsService(db)
  const defaultConfig = settingsService.getDefaultOpenCodeConfig()
  
  if (defaultConfig) {
    const merged = mergeDefaultMcpEntries(defaultConfig.content)
    if (JSON.stringify(merged.mcp) !== JSON.stringify(defaultConfig.content.mcp)) {
      settingsService.updateOpenCodeConfig(defaultConfig.name, { content: merged }, 'default')
      logger.info('Merged default MCP servers into default config')
    }
    const configPath = getOpenCodeConfigFilePath()
    const configContent = JSON.stringify(merged, null, 2)
    await writeFileContent(configPath, configContent)
    logger.info(`Synced default config '${defaultConfig.name}' to: ${configPath}`)
  } else {
    logger.info('No default OpenCode config found in database')
  }
}

try {
  await ensureEnvFile()
  await ensureDirectoryExists(getWorkspacePath())
  await ensureDirectoryExists(getReposPath())
  await ensureDirectoryExists(getConfigPath())
  logger.info('Workspace directories initialized')
  
  await cleanupOrphanedDirectories(db)
  logger.info('Orphaned directory cleanup completed')
  
  await cleanupExpiredCache()
  
  PORT = await prepareBackendPort(PORT)
  
  await ensureDefaultConfigExists()
  await syncDefaultConfigToDisk()
  await migrateConfigMapToFiles(db)
  await syncDefaultConfigToDisk()
  await ensureGlobalRulesFile()
} catch (error) {
  logger.error('Failed to initialize workspace:', error)
}

app.route('/api/repos', createRepoRoutes(db))
app.route('/api/settings', createSettingsRoutes(db))
app.route('/api/schedules', createScheduleRoutes(db))
  app.route('/api/permission-rules', createPermissionRuleRoutes(db))
  app.route('/api/untracked-suggestions', createUntrackedSuggestionsRoutes(db))
  app.route('/api/health', createHealthRoutes(db))
app.route('/api/files', createFileRoutes(db))
app.route('/api/providers', createProvidersRoutes())
app.route('/api/tts', createTTSRoutes(db))
app.route('/api/registry', createRegistryRoutes())
app.route('/api/config-files', createConfigFileRoutes(db))
app.route('/api/preview', createPreviewRoutes())
app.route('/api/command-runs', createCommandRunRoutes(db))
app.route('/api/search', createSearchRoutes(db))
app.route('/api/session-status', createSessionStatusRoutes(db))
app.route('/api/chat-queue', createChatQueueRoutes())
app.route('/api/logs', createClientLogRoutes())

app.get('/api/openapi.json', (c) => c.json(openApiSpec))

app.get('/api/docs', (c) => {
  return c.html(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OpenCode WebUI - Backend API</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
  <style>
    body { margin: 0; }
    .swagger-ui .topbar { display: none; }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    window.onload = () => {
      SwaggerUIBundle({
        url: '/api/openapi.json',
        dom_id: '#swagger-ui',
        deepLinking: true,
        persistAuthorization: true,
      })
    }
  </script>
</body>
</html>`)
})

app.all('/api/opencode/*', async (c) => {
  return proxyRequest(c.req.raw, c.req.method, c.req.path, c.req.query())
})

const isProduction = ENV.SERVER.NODE_ENV === 'production'

if (isProduction) {
  // Embedded frontend first: when the exe was packaged with
  // scripts/generate-frontend-embed.ts, everything is served from memory and
  // no frontend/dist folder needs to ship next to the binary. When embedded
  // assets exist, the disk fallback is disabled entirely so a stale dist
  // folder can never serve mismatched chunks.
  app.use('/*', async (c, next) => {
    if (c.req.method !== 'GET' && c.req.method !== 'HEAD') return next()
    if (c.req.path.startsWith('/api/')) return next()
    const route = c.req.path === '/' ? '/index.html' : decodeURIComponent(c.req.path)
    const asset = await getEmbeddedAsset(route)
    if (!asset) return next()
    c.header('Content-Type', asset.contentType)
    c.header('Cache-Control', asset.immutable ? 'public, max-age=31536000, immutable' : 'no-cache')
    return c.body(new Uint8Array(asset.body))
  })

  const embeddedAvailable = await hasEmbeddedAssets()
  if (!embeddedAvailable) {
    app.use('/*', serveStatic({ root: './frontend/dist' }))
  }

  app.get('*', async (c) => {
    if (c.req.path.startsWith('/api/')) {
      return c.notFound()
    }
    const embeddedIndex = await getEmbeddedAsset('/index.html')
    if (embeddedIndex) {
      c.header('Content-Type', 'text/html; charset=utf-8')
      c.header('Cache-Control', 'no-cache')
      return c.body(new Uint8Array(embeddedIndex.body))
    }
    const fs = await import('fs/promises')
    const path = await import('path')
    const indexPath = path.join(process.cwd(), 'frontend/dist/index.html')
    const html = await fs.readFile(indexPath, 'utf-8')
    return c.html(html)
  })
} else {
  app.get('/', (c) => {
    return c.json({
      name: 'OpenCode WebUI',
      version: '2.0.0',
      status: 'running',
      endpoints: {
        health: '/api/health',
        repos: '/api/repos',
        settings: '/api/settings',
        schedules: '/api/schedules',
        sessions: '/api/sessions',
        files: '/api/files',
        providers: '/api/providers',
        opencode_proxy: '/api/opencode/*',
        command_runs: '/api/command-runs'
      }
    })
  })

  app.get('/api/network-info', async (c) => {
    const os = await import('os')
    const interfaces = os.networkInterfaces()
    const ips = Object.values(interfaces)
      .flat()
      .filter(info => info && !info.internal && info.family === 'IPv4')
      .map(info => info!.address)
    
    const requestHost = c.req.header('host') || `localhost:${PORT}`
    const protocol = c.req.header('x-forwarded-proto') || 'http'
    
    return c.json({
      host: HOST,
      port: PORT,
      requestHost,
      protocol,
      availableIps: ips,
      apiUrls: [
        `${protocol}://localhost:${PORT}`,
        ...ips.map(ip => `${protocol}://${ip}:${PORT}`)
      ]
    })
  })
}

let isShuttingDown = false
let healthCheckInterval: NodeJS.Timeout | null = null
let scheduleRunner: NodeJS.Timeout | null = null

const shutdown = async (signal: string) => {
  if (isShuttingDown) return
  isShuttingDown = true
  
  logger.info(`${signal} received, shutting down gracefully...`)
  if (healthCheckInterval) clearInterval(healthCheckInterval)
  if (agentBrowserWarmupInterval) clearInterval(agentBrowserWarmupInterval)
  if (scheduleRunner) clearInterval(scheduleRunner)
  stopSessionStatusPoller()
  stopAutomationWatcher()
  stopGitCommitIndexer()
  try {
    await opencodeServerManager.stop()
    logger.info('OpenCode server stopped')
  } catch (error) {
    logger.error('Error stopping OpenCode server:', error)
  }
  if (httpServer) {
    await new Promise<void>((resolve) => {
      const timer = setTimeout(() => {
        logger.warn('HTTP server close timed out (5s); forcing exit')
        resolve()
      }, 5000)
      httpServer?.close(() => {
        clearTimeout(timer)
        resolve()
      })
    })
    httpServer = null
  }
  stopConverter()
  process.exit(0)
}

process.on('SIGTERM', () => shutdown('SIGTERM'))
process.on('SIGINT', () => shutdown('SIGINT'))
for (const signal of ['SIGBREAK', 'SIGHUP']) {
  try {
    process.on(signal, () => shutdown(signal))
  } catch {
    // signal not supported on this runtime/platform
  }
}

let httpServer: ReturnType<typeof serve> | null = null

const startServer = async (retries = 2): Promise<void> => {
  try {
    await new Promise<void>((resolve, reject) => {
      const server = serve({
        fetch: app.fetch,
        port: PORT,
        hostname: HOST,
      })
      httpServer = server
      server.on('listening', () => resolve())
      server.on('error', (err: NodeJS.ErrnoException) => reject(err))
    })
  } catch (error: any) {
    if (error.code === 'EADDRINUSE' && retries > 0) {
      logger.error(`Port ${PORT} is already in use. Free it or change PORT in .env and restart.`)
      await prepareBackendPort(PORT)
      return startServer(retries - 1)
    }
    throw error
  }
  logger.info(`🚀 OpenCode WebUI API running on http://${HOST}:${PORT}`)
}

const startupSettings = new SettingsService(db)
opencodeServerManager.setPreferredBinPath(startupSettings.getSettings().preferences.opencodeBin ?? null)

for (const repo of listRepos(db)) {
  try {
    if (writeRepoOpenCodeConfig(repo.localPath)) {
      logger.info(`Ensured per-repo OpenCode config for repo ${repo.localPath}`)
    }
  } catch (error) {
    logger.warn(`Failed to write per-repo OpenCode config for ${repo.localPath}:`, error)
  }
}

async function warmUpAllAgentBrowserDaemons(): Promise<void> {
  const namespaces = new Set<string>(['opencode'])
  for (const repo of listRepos(db)) {
    namespaces.add(repoAgentBrowserNamespace(repo.localPath))
  }
  for (const namespace of namespaces) {
    await warmUpAgentBrowserDaemon(namespace)
  }
}

opencodeServerManager.spawnNow()
warmUpAllAgentBrowserDaemons().catch((error) => {
  logger.error('Agent-browser daemon warm-up error:', error)
})

await startServer()

// Windows orphans children when the backend is force-killed (window close,
// taskkill /F), leaving opencode/agent-browser processes and stale ports
// behind. The watchdog reaps our children whenever this PID exits.
installWindowsShutdownWatchdog()

opencodeServerManager.start()
  .then(() => {
    logger.info(`OpenCode server running on port ${opencodeServerManager.getPort()}`)
  })
  .catch((error) => {
    logger.error('Failed to start OpenCode server:', error)
  })

healthCheckInterval = setInterval(() => {
  opencodeServerManager.ensureRunning().catch((error) => {
    logger.error('Failed to ensure OpenCode server is running:', error)
  })
}, ENV.TIMEOUTS.HEALTH_CHECK_INTERVAL_MS)

let agentBrowserWarmupInterval: NodeJS.Timeout | null = null
agentBrowserWarmupInterval = setInterval(() => {
  warmUpAllAgentBrowserDaemons().catch((error) => {
    logger.error('Agent-browser daemon re-warm-up error:', error)
  })
}, 60_000)

scheduleRunner = startScheduleRunner(db)
logger.info('Schedule runner started')

startSessionStatusPoller(db)
logger.info('Session status poller started')

startGitCommitIndexer(db)
logger.info('Git commit indexer started')

startAutomationWatcher()