import { readdirSync, statSync, existsSync, mkdirSync, writeFileSync } from 'fs'
import { join, relative, posix, dirname } from 'path'

const root = join(import.meta.dir, '..')
const distDir = join(root, 'frontend', 'dist')
const outFile = join(root, 'backend', 'src', 'generated', 'frontend-embed.generated.ts')

if (!existsSync(distDir)) {
  console.error(`[embed] frontend dist not found: ${distDir}`)
  console.error('[embed] run `pnpm run build:frontend` first')
  process.exit(1)
}

function walk(dir: string, base = ''): string[] {
  const out: string[] = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const rel = base ? posix.join(base, name) : name
    if (statSync(full).isDirectory()) out.push(...walk(full, rel))
    else out.push(rel)
  }
  return out.sort()
}

const files = walk(distDir)
if (files.length === 0) {
  console.error(`[embed] no files in ${distDir}`)
  process.exit(1)
}
const routes = files.map((rel) => (rel === 'index.html' ? '/' : `/${rel}`))

const imports = files
  .map((file, i) => `import f${i} from '../../../frontend/dist/${file}' with { type: 'file' }`)
  .join('\n')

const entries = routes
  .map((route, i) => `  { route: '${route.replace(/'/g, "\\'")}', path: f${i} },`)
  .join('\n')

const content = `// AUTO-GENERATED by scripts/generate-frontend-embed.ts - do not edit.
// @ts-nocheck
${imports}

export interface EmbeddedFileEntry {
  route: string
  path: string
}

export const embeddedFiles: EmbeddedFileEntry[] = [
${entries}
]
`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, content, 'utf8')
console.log(`[embed] wrote ${files.length} entries -> ${relative(root, outFile)}`)
