import { readdirSync, statSync, writeFileSync } from 'fs'
import { join, relative, posix } from 'path'

const root = join(import.meta.dir, '..')
const distDir = join(root, 'frontend', 'dist')
const outFile = join(root, 'backend', 'src', 'generated', 'frontend-embed.generated.ts')

function walk(dir: string, base = ''): string[] {
  const out: string[] = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const rel = base ? posix.join(base, name) : name
    if (statSync(full).isDirectory()) out.push(...walk(full, rel))
    else out.push(rel)
  }
  return out.sort()
}

const files = walk(distDir)
const routes = files.map((rel) => (rel === 'index.html' ? '/' : `/${rel.split('\\').join('/')}`))

const imports = files
  .map((_, i) => `import f${i} from '../../../frontend/dist/${files[i].split('\\').join('/')}' with { type: 'file' }`)
  .join('\n')

const entries = routes
  .map((route, i) => `  { route: '${route}', path: f${i} },`)
  .join('\n')

const content = `// AUTO-GENERATED by scripts/generate-frontend-embed.ts - do not edit.
// @ts-nocheck
${imports}

export interface EmbeddedFileEntry {
  route: string
  path: string
}

export const embeddedFiles: EmbeddedFileEntry[] = [
${entries}
]
`

writeFileSync(outFile, content, 'utf8')
console.log(`[embed] wrote ${files.length} entries -> ${relative(root, outFile)}`)
